### ISSUE TITLE
Dingus CSS errors

### ISSUE THREAD

**Issue by flying-sheep** [jgm/CommonMark#319]
Hi, the textarea in http://spec.commonmark.org/dingus has two CSS bugs:

1. It has `white-space: nowrap`, which, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space)

	> Collapses whitespace as for normal, but suppresses line breaks (text wrapping) within text.

	And yes, consequently, I can’t enter multiple lines in the textarea: all newlines are treated as spaces. This is how it looks for me (text selected for clarity):

	![easy1](https://cloud.githubusercontent.com/assets/291575/7372524/810bb6d0-edc7-11e4-8e93-0f8ba0a0a33f.png)

2. This is a bootstrap thing, but there is a rule `button, input, optgroup, select, textarea { …; color: inherit; }`.

	That means “take the text color from the parent element, but leave the default background color”

	On my system, both those colors happen to be black (textareas are yellow-on-black per default)

the second one is mainly my unusual setup (even though explicitly setting both background and foreground would be nice)

but the first one is just crazy. did noone try this on a standards-compliant browser?

**Comment by jgm** [comment]
This is embarrassing.  I admit, I only tried the latest version in Chrome.

So, what's the right way to ensure that lines don't "soft wrap" in the text box?  (That is, lines longer than the the width of the text box should trigger a horizontal scroll bar rather than wrapping to the next tline.)  Soft wrapping messes up the algorithm for determining source position.  If I replace `white-space: nowrap` with `white-space: pre`, then it works correctly in Firefox (which does what the CSS documentation leads one to expect), but then I get soft wrapped lines in Chrome.  Is there a way to get the right behavior in both (and in IE)?

Also, if you want to suggest some specific CSS changes for the background color issue, please do.

**Comment by jgm** [comment]
Ah:  `word-wrap: normal` did the trick.

**Comment by jgm** [comment]
This commit didn't fix the background/foreground color issue -- I'm not sure precisely what you have in mind, but if you want to suggest something, please go ahead.

**Comment by flying-sheep** [comment]
apparently the html attribute `wrap="off"` also does the trick, but i don’t see it in any standard. so `word-wrap: normal` seems preferable.

about background and color:

either you could set both to sensible values (black on white or so), or you undo what bootstrap does via `color: -moz-FieldText`.

**Comment by flying-sheep** [comment]
oh, and: thanks :smile:

**Comment by jgm** [comment]
+++ Philipp A. [Apr 28 15 09:37 ]:
>   either you could set both to sensible values (black on white or so), or
>   you undo what bootstrap does via color: -moz-FieldText.

Are you talking about setting color/background on just the
textarea, or would it suffice to set it for the body element?

**Comment by flying-sheep** [comment]
for the textarea. body is black on white for me, textarea yellow on black. setting only one of both for the textarea (like bootstrap does) will make it black-on-black or yellow-on-white
