### ISSUE TITLE
Should a code block interrupt a block quote in case of a lazy paragraph continuation?

### ISSUE THREAD

**Issue by opennota** [jgm/CommonMark#328]
```
> block quote
....code block
```

Should `code block` continue the block quote or should it terminate it?

Spec v0.19:

> Laziness only applies to lines that are continuations of paragraphs. Lines containing characters or indentation that indicate block structure cannot be lazy.

but

> An indented code block cannot interrupt a paragraph.

**Comment by cebe** [comment]
block elements can not be used in a lazy fashion. if you want the code inside of the block quote you have to do it explicitly:

~~~~

> block
> ```
code
code
...
```

~~~~

**Comment by opennota** [comment]
@cebe Your example is wrong (see [example 150](http://spec.commonmark.org/0.19/#example-150)) and doesn't answer the question.

What I'm asking is, how
```
> block quote
....code block
```
will render, as a block quote
```
<blockquote><p>block quote code block</p></blockquote>
```
or two sequential blocks, a block quote and a code block:
```
<blockquote><p>block quote</p></blockquote>
<pre><code>code block</code></pre>
```

**Comment by jgm** [comment]
+++ opennota [Jun 03 15 04:43 ]:
>> block quote
>....code block
>
>   Should code block continue the block quote or should it terminate it?

The line "code block" continues the paragraph inside the
code block.

Here is a way to see this.  If you had

```
block quote
   code block
```

that would be a paragraph with a lazy continuation.

The rules for block quotes say that if we put `> ` in front
of every line, we get this paragraph in a block quote:

```
> block quote
>    code block
```

The rule for laziness governing block quotes (#2 in 5.1) say
that we can delete the `> ` on the second line and still get
something with the same meaning:

```
> block quote
    code block
```

So I hope that is clear enough.  But you might be bothered
by the following question:  granting that the spec says
this may be parsed as a block quote with a single paragraph,
why doesn't it ALSO say it may be parsed as a block quote
followed by a code block?  (That is, why isn't there an
inconsistency or ambiguity here?)

The spec for indented code blocks says that they can't
interrput paragraphs, but if we thought of the structure as

```
<blockquote>
<p>block quote</p>
</blockquote>
<pre><code>code block
</code></pre>
```

then it looks like the code block isn't interrupting a
paragraph, since the paragraph was closed before the end of
the blockquote.

Is that the concern?  Do you have any suggestions about how
to make the spec clearer on this point?

**Comment by opennota** [comment]
@jgm 
> The line "code block" continues the paragraph inside the
code block.

Did you mean "inside the block quote?"

**Comment by jgm** [comment]
+++ opennota [Jun 04 15 01:37 ]:
>   [1]@jgm
>
>     The line "code block" continues the paragraph inside the
>     code block.
>
>   Did you mean "inside the block quote?"

Yes.

**Comment by opennota** [comment]
The spec says
> Lines containing characters or indentation that indicate block structure cannot be lazy.

and it is followed by the example 147:
```
> foo
---
```

so it is unclear whether an indented code block should follow the same rule.

I think some clarification is needed here. Like,
> Lines containing characters or indentation that indicate block structure **(except for indented lines, that would otherwise start code blocks)** cannot be lazy.
