### ISSUE TITLE
How should a CommonMark-compliant parser parse this and why?

### ISSUE THREAD

**Issue by opennota** [jgm/CommonMark#329]
```
>> 123
456
> 789
```

**Comment by jgm** [comment]
As
```
<blockquote>
<blockquote>
<p>123
456
789</p>
</blockquote>
</blockquote>
```

Why?  Start with
```
>> 123
>>456
>> 789
```
Now apply the [Laziness rule governing block quotes](http://spec.commonmark.org/0.19/#block-quotes) to the inner block quote, yielding the equivalent:
```
>> 123
>456
> 789
```
Finally, apply the laziness rule again, but just to the second line.

I'm going to close this issue, because the bug tracker is for bug reports.  More open-ended questions and requests for clarification should go to http://talk.commonmark.org.  Feel free to start a thread there if this answer doesn't satisfy you.
