### ISSUE TITLE
iframe should not be wrapped with paragraph

### ISSUE THREAD

**Issue by puzrin** [jgm/CommonMark#352]
Example (markdown):

```
before iframe

<iframe width="560" height="315" src="https://www.youtube.com/embed/pfBTXZWRPQ4" frameborder="0" allowfullscreen></iframe>

after iframe
```

It seems, `iframe` is missed in whitelist of block tags.

**Comment by jgm** [comment]
The spec is correct.  According to
http://www.w3.org/TR/2011/WD-html5-20110525/the-iframe-element.html#the-iframe-element
iframe can be used for "phrasing content" (i.e., inline).
So it is like del and ins, which can go either way.

Solution is to put the open tag on a line by itself:

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/pfBTXZWRPQ4" frameborder="0" allowfullscreen>
</iframe>
```

Or, put the whole thing in a div.

+++ Vitaly Puzrin [Jul 20 15 18:52 ]:

**Comment by puzrin** [comment]
IMHO that's not perfect. Main `iframe` use-case in embedding video players. Such code is autogenerated. Requirement to split it into multiline will cause huge number of human errors.

Iframe in phrasing content is theoretic use case, needed for browser devs only.

**Comment by jgm** [comment]
+++ Vitaly Puzrin [Jul 21 15 10:33 ]:
>   IMHO that's not perfect. Main iframe use-case in embedding video
>   players. Such code is autogenerated. Requirement to split it into
>   multiline will cause huge number of human errors.
>
>   Iframe in phrasing content is theoretic use case, needed for browser
>   devs only.

I have no idea what the real use cases for this are.  You
may be right that we should sacrifice principle here, but
note that doing so would make it *impossible* to express
iframes in inline contexts.  And I don't like to make things
unexpressable.

I think this might be a good topic to raise on talk.

**Comment by toddself** [comment]
Version 0.18.2 did NOT wrap `<iframe>` tags in a `<p>` tag so this is a regression.

I have an HTML->Markdown converter that has a test suite to confirm roundtrip testing through several Markdown->HTML converters including conformance with Gruber's original version.  I just upgraded my CommonMark version from 0.18.2 to 0.21.0 and this test is now failing again.

I originally reported this in #88 where it was fixed.

**Comment by puzrin** [comment]
@toddself See talk on the forum http://talk.commonmark.org/t/raw-html-blocks-proposals-comments-wanted/983/66?u=vitaly.

**Comment by jgm** [comment]
+++ Todd Kennedy [Aug 17 15 09:18 ]:
>Version 0.18.2 did NOT wrap `<iframe>` tags in a `<p>` tag so this is a regression.

The spec for HTML blocks changed for many good reasons.  One
upshot was that `<iframe>` gets treated differently.
This is because `<iframe>` is no longer on the whitelist of tags
that can only be used in block-level content.  It is legal
in HTML to use `<iframe>` inside a `<p>` tag.  So, the
current spec treats `<iframe>` like `<del>`, as a tag that
might be either block-level or inline-level.  If the initial
tag is on a line by itself, it is treated as block-level,
otherwise it is considered part of a paragraph
(inline-level).

I hope that explains the change.  In the talk.commonmark.org
thread linked above, there is a proposal to put `<iframe>`
in the list of tags that are always treated as starting an
HTML block, even though in principle it should not be.
I'm sympathetic to the arguments that have been given and
will probably make this change in a future version of the
spec.

**Comment by toddself** [comment]
thanks for the reply @jgm -- i made a comment on the forum about the difficulties we have with styling content in some real-world scenarios where `<iframe>` tags are wrapped in `<p>` tags automatically.
