### ISSUE TITLE
Syntax highlighting indented code

### ISSUE THREAD

**Issue by ioquatix** [jgm/CommonMark#363]
I believe it should be possible to syntax highlight indented code. Presently, this does not appear to be possible.

Discussion was had here: https://github.com/github/markup/issues/540#issuecomment-133816948

Ideally, somehow, it would be possible to have raw code blocks (indented by tabs or 2+ spaces) and also specify which language should be used for syntax highlighting.

**Comment by jgm** [comment]
One thing the OP in the linked issue wanted to be able to do
is use backtick code blocks, but indent them slightly for
readability, so they stand out more from the text.  You can
do that in CommonMark, as long as you don't indent them 4 or
more spaces (for then they're treated as indented code
blocks).

As for highlighting in indented code blocks, there would
need to be a way of specifying the language.  One
possibility would be to adopt some kind of conventon,
e.g. if the first line is `[ruby]`, then the rest is
highlighted as ruby (and the first line stripped off).

With the reference parsers you can implement this convention
easily enough.  You just need to traverse the AST looking
for code blocks (use the iterator interface), and modify
ones htat begin in this way.  Or you could use a custom
renderer.

One might propose that such a convention be formalized in
the spec. The place to raise this issue is not here, though,
but in the forum <http://talk.commonmark.org>.  This tracker
is for focused issues that don't require extensive
discussion.

+++ Samuel Williams [Aug 23 15 04:09 ]:

**Comment by ioquatix** [comment]
Okay, I signed into the forum and immediately the submission box filled up with Korean spam. That forum might be hacked?

Anyway, I managed to start this: http://talk.commonmark.org/t/syntax-highlighting-indented-code/1840

**Comment by jgm** [comment]
@codinghorror, can you look into the spam/possible hacking issue?  I'll close this issue, since comments should go onto the forum.  Thanks.

**Comment by coding-horror** [comment]
We have no evidence that this is the case. I wonder if somehow you shared an old topic draft with one of the bamwar Korean spammers? We will look into it.

**Comment by ioquatix** [comment]
Yeah it was bamwar

**Comment by ioquatix** [comment]
Okay, so after posting this to the forum... 3 months ago? there was no real discussion. So.. what's the next step?

**Comment by jgm** [comment]
+++ Samuel Williams [Nov 30 15 19:15 ]:
>   Okay, so after posting this to the forum... 3 months ago? there was no
>   real discussion. So.. what's the next step?

The fact that nobody commented may indicate that not many
people have a need for this.  (After all, you can already
mark up fenced code blocks with a syntax.)  I don't think
there's a compelling case for putting this in the spec.
And there's a case against it -- it might break some
existing Markdown documents.

As noted above, you could always customize a CommonMark
parser to follow a convention, such as:  if the first line
of a code block is `[LANG]`, highlight the rest as LANG
code.

**Comment by ioquatix** [comment]
Is markdown supposed to be a human readable format?
