### ISSUE TITLE
Add U+00A0 (NO-BREAK SPACE) as whitespace

### ISSUE THREAD

**Issue by wdhwg001** [jgm/CommonMark#366]
Both ES5 and jQuery treat `\xA0` as whitespace in String.prototype.trim()

**Comment by jgm** [comment]
It's not clear that this is desirable.

Currently all the characters that relate to block structure in Markdown are ASCII; adding U+00A0 as whitespace would break this.  That's a move away from simplicity, and if we allow U+00A0, what about all the other unicode space characters (half-width space, zero-width space, etc.)?

The structural-markers-are-ASCII invariant also helps in writing parsers that process text as streams of bytes (e.g. in C).

Finally, allowing nonbreaking space NOT to count as whitespace also opens up some expressive possibilities -- e.g.  if you want some emphasized text that begins and ends with a space, you can do it using nonbreaking spaces, but you wouldn't be able to if we made the proposed change.

+++ wdhwg001 [Sep 09 15 04:20 ]:

**Comment by lancedolan** [comment]
I offer the following as a deeply respectful argument toward supporting the unicode whitespace as whitespace. Sometimes criticisms can be taken a bit personally, and I want to be clear that I'm criticisnig a decision and not any person.

The decision **not** to support unicode whitespace characters as white space characters has exactly the merits @jgm has given, but those merits don't seem to hold up against the "spirit" of markdown in the context of the internet, in which unicode whitespace shows up fairly often, and the intuition of developers and users alike is that unicode whitespace is, in fact, whitespace.

With the current spec, we have the ability to provide a type of whitespace that is, sheerly by unexpected specification/convention, not whitespace, in order to trigger unexpected parsing appears. This appears, to me, a counterintuitive secret-handshake and hack akin to poorly named methods or so many anti patterns I've recommended against, rather than a desirable opportunity to be more expressive.

This cost me a solid day of development time to track down the culprit today, resulting in [this issue report](https://github.com/markdown-it/markdown-it/issues/541), and I'm really kind of shocked to see this. I'm only one voice and my experience will probably be brushed aside, but it seems obvious to me that others should be experiencing issues due to this in various places (I see @maximbaz hit [an issue](https://github.com/remarkjs/remark/issues/321) as well.

Thanks for your consideration and dedication to such a valuable project. 

:)

**Comment by digitalmoksha** [comment]
I think there is something to be said for keeping it simple in regards to structural whitespace. Considering there are at least 20 Unicode whitespace characters (at least according to this: http://jkorpela.fi/chars/spaces.html ) and an ASCII whitespace is available everywhere, I personally consider it reasonable.
