### ISSUE TITLE
spec.txt - use fenced code blocks for examples

### ISSUE THREAD

**Issue by Knagis** [jgm/CommonMark#379]
[The issue in the dingus](http://spec.commonmark.org/dingus/?text=The%20end%20tag%20can%20occur%20on%20the%20same%20line%20as%20the%20start%20tag%3A%0A%0A.%0A%3Cstyle%3Ep%7Bcolor%3Ared%3B%7D%3C%2Fstyle%3E%0A*foo*%0A.%0A%3Cstyle%3Ep%7Bcolor%3Ared%3B%7D%3C%2Fstyle%3E%0A%3Cp%3E%3Cem%3Efoo%3C%2Fem%3E%3C%2Fp%3E%0A.%0A%0A)

The issue reported on the .NET port: <https://github.com/Knagis/CommonMark.NET/issues/50>

Short version:

````
.
<style>p {color:red}</style>
.
````

Gets interpreted as HTML by a markdown parser and thus embeds a style tag in the resulting document.

My proposal would be to change it to something [like this](http://spec.commonmark.org/dingus/?text=The%20end%20tag%20can%20occur%20on%20the%20same%20line%20as%20the%20start%20tag%3A%0A%0A%60%60%60%60%0A%3Cstyle%3Ep%7Bcolor%3Ared%3B%7D%3C%2Fstyle%3E%0A*foo*%0A%60%60%60%60%0A%60%60%60%60%0A%3Cstyle%3Ep%7Bcolor%3Ared%3B%7D%3C%2Fstyle%3E%0A%3Cp%3E%3Cem%3Efoo%3C%2Fem%3E%3C%2Fp%3E%0A%60%60%60%60%0A):

    ````markdown
    <style>p{color:red;}</style>
    *foo*
    ````
    ````html
    <style>p{color:red;}</style>
    <p><em>foo</em></p>
    ````

**Comment by jgm** [comment]
`spec.txt` isn't intended to be interpreted as a Markdown file.
If you want a Markdown version, do `make spec.md`.

Adding all of that boilerplate (to add example divs and proper code blocks surrounding the examples) would make it much more cumbersome to write the spec, and also harder to read in its plain text form.  That's why I adopted the ad hoc shorthand using `.` separators for the examples.  (Also, some of the spec tests involve code fences, so one must be careful to use more backticks for the delimiter lines.)

**Comment by Knagis** [comment]
Reading this now reminds me that this wasn't the first time someone raised the same issue and the same explanation was given. Sorry about that!
