### ISSUE TITLE
Converting special unicode characters to HTML entities

### ISSUE THREAD

**Issue by awalGarg** [jgm/CommonMark#396]
Presently, `&` is converted to `&amp;`, `<` to `&lt;` etc. at suitable locations. I propose that we should also be converting `•` to `&bull;` and similarly for all other identified entities because:

1. consistency
2. most major browsers try to render these characters in the ASCII range (so • is rendered as â€¢) when the charset is not declared as utf8.

The list of these entities shall conform to same list as specified in http://spec.commonmark.org/0.24/#entity-references (https://html.spec.whatwg.org/entities.json).

Apologies if this has been discussed before and rejected for some reason. I wasn't able to find it in the issue tracker.

**Comment by jgm** [comment]
+++ Awal Garg [Mar 01 16 09:55 ]:
>   Presently, & is converted to &amp;, < to &lt; etc. at suitable
>   locations. I propose that we should also be converting • to &bull; and
>   similarly for all other identified entities because:
>    1. consistency
>    2. most major browsers try to render these characters in the ASCII
>       range (so • is rendered as â€¢) when the charset is not declared as
>       utf8.

So, declare the charset!

We could add an option to use entities for all non-ASCII
characters (like pandoc's `--ascii`), but in general it's
better to declare the charset in a meta tag.  Using
entities makes the source less readable and increases its
size.

**Comment by awalGarg** [comment]
@jgm I agree that declaring the charset explicitly is better than relying on this. But _**consistency**_ is still a great reason to do this. And sometimes, it is not possible to declare charset (submitting markdown to a third-party). Using HTML entities in markdown itself will make _markdown_ source unreadable and large - which will be a big step backwards. Converting them to HTML entities avoids the problem altogether.

> Using entities makes the source less readable and increases its size.

I see your reasoning clearly :) But markdown's popularity is based on the fact that HTML _is_ unreadable and more verbose than it needs to be for specific usecases (I recognize that this is a weak argument from my side :)). And using entities is, in any case, a more HTML-ish solution than dropping unicode chars in source.

I didn't know about Pandoc's switch, thanks for that!

I also agree that this is not the most shining all of proposals. It is "low-priority", but I would still press on re-considering it for the above reasons. It might not be useful for every other situation, but it won't be harmful at all. After all, it applies only when you actually use unicode special chars in markdown, which, while not rare, is uncommon :) I am willing to draft this amendment in specification and also patch the current canonical implementations in this repo, if you can give this a green "planned (but low-priority)" flag.

Thanks for your patience.

**Comment by jgm** [comment]
+++ Awal Garg [Mar 02 16 00:20 ]:
>   [1]@jgm I agree that declaring the charset explicitly is better than
>   relying on this. But consistency is still a great reason to do this.

I don't see the consistency argument.  We use unicode
characters whenever we can, using entities only for
characters like `&` and `<` that *have* to be escaped.
That's a perfectly reasonable rule.

(If you really want *every* character to be treated the same,
we could encode *every* character, including ASCII
characters, as numerical entities.  But it would be absurd
to do that in the name of "consistency.")

>   And sometimes, it is not possible to declare charset (submitting
>   markdown to a third-party). Using HTML entities in markdown itself will
>   make markdown source unreadable and large - which will be a big step
>   backwards. Converting them to HTML entities avoids the problem
>   altogether.

Note that even if you use entities in the markdown source,
they'll be rendered as unicode characters, not entities.

I have no objection to implementations providing an option
to produce the sort of output you prefer (or even doing this
by default -- though I'm not going to change the reference
implementations to do this, because I think the current
default is preferable).  The CommonMark spec does not
specify the details of the HTML output; it just defines a
mapping from source text to a structured document.  Since
the spec test runner does normalization, your implementation
will pass the tests whether it produces `&copy;` or `©`.

>   won't be harmful at all. After all, it applies only when you actually
>   use unicode special chars in markdown, which, while not rare, is
>   uncommon :)

unless you happen to be one of the billions of people who
writes in a language other than English!

>   I am willing to draft this amendment in specification and
>   also patch the current canonical implementations in this repo, if you

It's not a spec issue, as explained above.  The spec doesn't
get into details of HTML rendering.  The examples use a
particular rendering, but this is out of practicality, and
eventually we'd like to use an XML version of the AST
instead of HTML for the examples.

**Comment by awalGarg** [comment]
>  (If you really want *every* character to be treated the same, we could encode *every* character, including ASCII characters, as numerical entities. But it would be absurd to do that in the name of "consistency.")

No, I'd like special characters which have legible entities defined in the list I linked. Presently it contains 2231 entities, as compared to the 1114112 characters possible in unicode. So just 0.2% of the total number possible. Obviously rendering everything in numerical entities is silly.

> unless you happen to be one of the billions of people who writes in a language other than English!

That's a very strong point which I missed. Thanks for pointing it out!

> It's not a spec issue, as explained above. The spec doesn't get into details of HTML rendering. The examples use a particular rendering, but this is out of practicality

Okay. Apparently I missed that.

Thank you for taking the time to explain this! I am satisfied by your reasoning and am closing this issue :)
