### ISSUE TITLE
Inconsistent <img> handling

### ISSUE THREAD

**Issue by glebm** [jgm/CommonMark#434]
The `<img>` tag handling seems to depend on how the tag is closed.

[Demo dingus](https://goo.gl/zZv8e5).

**Comment by jgm** [comment]
This is all in accordance with the spec.

In the second group you have a type 7 raw HTML block.
http://spec.commonmark.org/0.26/#html-block
Because the img tag is by itself on the line, the rest
(up to blank line) gets counted as raw HTML (and hence
not interpreted as Markdown).  If you put the Markdown
image on the same line, you'll get a paragraph with the
two images.

In the third group it's the same situation, but renders
differently in browsers because of the unclosed img tag.

+++ Gleb Mazovetskiy [Nov 06 16 10:52 ]:

**Comment by glebm** [comment]
It doesn't seem like the first version should be any different then:

```ruby
<img src="x"></img> # <-- does not satisfy any ending conditions for type 7
![img][img] # <-- is processed
```

```ruby
<img src="x" /> # <-- does not satisfy any ending conditions for type 7
![img][img] # <-- is not processed
```

The larger issue is that the CommonMark spec doesn't account for [void elements](http://w3c.github.io/html/syntax.html#void-elements) correctly, but I'll raise that in the spec repo

**Comment by jgm** [comment]
+++ Gleb Mazovetskiy [Nov 06 16 11:49 ]:
>   It doesn't seem like the first version should be any different then:
>
><img src="x"></img> # <-- does not satisfy any ending conditions for type 7
>![img][img] # <-- is processed

This case does not satisfy the start condition for type 7,
since you have two tags on the first line.

><img src="x" /> # <-- does not satisfy any ending conditions for type 7
>![img][img] # <-- is not processed

This case does satisfy the start condition for type 7,
given the official definition of open tag (follow the link),
which includes a self-closing tag.

The end condition is satisfied by the blank line.

**Comment by glebm** [comment]
Oh, I see, missed the "followed only by whitespace or the end of the line" for condition 7.
Since this is not an implementation bug, I'm closing this.
