### ISSUE TITLE
Whitespace should be allowed after link label in inline links [] ()

### ISSUE THREAD

**Issue by Lanchon** [jgm/CommonMark#471]
whitespace should be allowed after link label in inline links.

rationale:

```
1- in plain text documents, [long link labels and their
links](http://some.long.url/that-is-aweful-to-see.html) look horrible
when part of the label sticks to the URL for line wrap.

comparatively, [long link labels and their links]
(http://some.long.url/that-is-aweful-to-see.html) look better if space
is allowed between label and link and line wrap can occur there.
```

2- github and gitlab have tonnes of content that is broken by the current spec. really, what's the use of bablemark if it doesn't take into account the volume of text currently being rendered by each markdown processor?

here is a couple of my projects that are currently horribly broken by this:
https://github.com/Lanchon/haystack/blob/master/README.md
https://github.com/Lanchon/REPIT/blob/master/README.md

3- a similar issue exists with reference links, only that one breaks even the first markdown implementations:
https://talk.commonmark.org/t/why-are-whitespaces-allowed-after-reference-link-label-but-not-for-inline-links/447

maybe a more clever solution than disallowing whitespace could be agreed upon for both of these cases, instead of simply breaking so much content?

thanks!

**Comment by Lanchon** [comment]
btw, see that in [this section] (https://github.com/Lanchon/haystack/blob/master/README.md#signature-spoofing-patcher-for-android) the images are also not being rendered by this same issue!

**Comment by jgm** [comment]
I think that this rationale -- line breaking -- is the only
good rationale for allowing spaces in such cases.

For inline links, only a few implementations ever allowed
the spaces between the link label and the URL part, and
Gruber's original syntax description says that the
parentheses must come "immediately after" the bracketed
part.

Because of this split, there is some content that assumes
that

    [blah] (parethetical)

will be a link to [blah] followed by a parenthetical,
and other content that takes it to be a link.

CommonMark has to choose, and either way some existing
content will be rendered differently.

We chose here to follow Gruber's syntax description,
the original perl script, and the vast majority of
implementations.

The decision for reference links was more controversial,
since Gruber's implementation allowed spaces here, and
they're even explicitly allowed by his syntax description.

Note, however, that when this syntax description was
written and the original Markdown.pl was designed, there
were not "shortcut reference links":  that is, you could
write

    [blah][foo]

    [foo]: url

or

    [foo][]

    [foo]: url

but not

    [foo]

    [foo]: url

With the introduction of shortcut reference links (in
a later beta of Markdown.pl, but never in the
documentation!), it became problematic to allow the
space between the two bracketed parts, since that created
an ambiguity.  Consider:

    [foo] [bar]

    [foo]: url1
    [bar]: url2

Is that a link to url2 with text 'foo', or two links with
text 'foo' to url1 and 'bar' to url2?

Hence we made the decision to forbid a space here.  Of
course the line wrapping consideration occurred to us, but
since we were already not allowing a space in inline links,
where this consideration made even more sense, it didn't
seem a compelling reason.

>   maybe a more clever solution than disallowing whitespace could be
>   agreed upon for both of these cases, instead of simply breaking so much
>   content?

Of course, we're always open to specific suggestions!
(Bonus if you implement it in the reference implementation
and run the test suite to see what else might break.)
